export enum AppRoutes {
  HOME = 'home',
  MENU = 'menu',
  SPORT = 'sport',
  LIVE = 'live',
  SLOT = 'slot',
  LOTTO = 'lotto',
  FISH = 'fish',
  // POKER = 'poker',
  BOARD = 'board',
  PLATFORM = 'platform',
  SlotCenter = 'slot-center',
  LOGIN = 'login',
  REGISTER = 'register',
  PUBLIC_QUEST = 'public-quest',
  PUBLIC_QUEST_DETAILS = 'public-quest-details',
  VIP = 'vip',
  BEGINNER = 'beginner',
  COMMON_PROBLEM = 'common-problem',
  SERVICE = 'service',
  ABOUT = 'about',
  JOIN_US = 'join-us',
  FORGET = 'forget',
  BULLETIN = 'bulletin',
  CONTACT = 'contact',
  POLICY = 'policy',
  CONFIRM_PRIORITY = 'confirm-priority',
  // member
  DEPOSIT = 'deposit',
  WITHDRAWAL = 'withdrawal',
  USER_INFO = 'user-info',
  BANK_CARD = 'bank-card',
  TRANSFER = 'transfer',
  TRADE_RECORD = 'trade-record',
  REVIEW_MAIN = 'reivew-main',
  REVIEW_ACTIVITY = 'reivew-activity',
  // REVIEW = 'review',
  Activity_Wallet = 'activity-wallet',
  // 舊優惠列表
  QUEST = 'quest',
  // 舊優惠 with tabs
  OLD_QUEST_CENTER = 'old-quest-center',
  // 舊優惠申請
  QUEST_APPLY = 'quest-apply',
  // 舊優惠紀錄
  QUEST_RECORED = 'quest-record',

  EMAIL = 'email',
  EMAIL_DETAILS = 'email-details',
  HELP = 'help',
  MERCHANTS = 'merchants',
  TRANSPOPUP = 'transfer-popup',
  MY_WALLET = 'my-wallet',
  LETTER = 'letter',
  LETTER_DETAIL = 'letter-detail',
  BET_LOG = 'bet-log',
}
